In [1]:
# Importing modules
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import sys

# Setting up the path to include the parent directory
sys.path.append(str(Path.cwd().parent.parent))
from backend.config.settings import PATHS
from backend.scraping.scrape_reservoirs import get_reservoir_province_rate_limited

In [2]:
reservoirs_path = PATHS['processed_data'] / 'post_cleaning' / 'reservoirs_cleaned.csv'
reservoirs_pd = pd.read_csv(reservoirs_path)
reservoirs_pd.head()

   id                         scope            name  capacity  electric_flag
0   1                  guadalquivir           brena       103              0
1   3                  guadalquivir      fernandina       247              0
2   5                  guadalquivir  puebla cazalla        87              0
3   6                  guadalquivir     pedro marin        19              0
4   9  cuenca mediterranea andaluza         vinuela       170              0

In [3]:
detailed_reservoirs_path = PATHS['processed_data'] / 'post_cleaning' / 'detailed_reservoirs_cleaned.csv'
detailed_reservoirs_pd = pd.read_csv(detailed_reservoirs_path)
detailed_reservoirs_pd.head()

,name,x,y,basin,riverbed,google,openstreetmap,wikidata,province,autonomous_community,type,crest_elevation,dam_height,report
0,santa ana,41.882506,0.580850,ebro,rio noguera ribagorcana,NaN,NaN,NaN,huesca,aragon,presa fabrica arco gravedad,380.30,99.6,https://sig.mapama.gob.es/WebServices/clientew...
1,tanes,43.220950,-5.427761,cantabrico occidental,rio nalon,NaN,NaN,NaN,asturias,principado asturias,presa fabrica gravedad (hormigon vibrado),495.00,95.0,https://sig.mapama.gob.es/WebServices/clientew...
2,val,41.875792,-1.786973,ebro,rio casa o val,NaN,NaN,https://www.wikidata.org/wiki/Q95570755,zaragoza,aragon,presa fabrica gravedad (hormigon compactado),629.15,94.4,https://sig.mapama.gob.es/WebServices/clientew...
3,peares,42.465137,-7.723744,mino sil,rio mino,https://www.google.com/search?kgmid=/g/155svy9k,NaN,https://www.wikidata.org/wiki/Q11986800,lugo,galicia,presa fabrica gravedad (hormigon vibrado),196.50,94.0,https://sig.mapama.gob.es/WebServices/clientew...
4,mediano,42.313617,0.210738,ebro,rio cinca,https://www.google.com/search?kgmid=/g/121bdb0g,https://www.openstreetmap.org/relation/7141904,https://www.wikidata.org/wiki/Q3215482,huesca,aragon,presa fabrica gravedad (hormigon vibrado),529.50,92.0,https://sig.mapama.gob.es/WebServices/clientew...

In [4]:
merged_pd = pd.merge(reservoirs_pd, detailed_reservoirs_pd, on='name', how='outer')
not_paired_reservoirs = merged_pd[(merged_pd['id'].isnull()) | (merged_pd['x'].isnull())]['name'].copy()
not_paired_reservoirs.sort_values(inplace=True)

# Let's display all not paired reservoirs
pd.set_option('display.max_rows', None)
not_paired_reservoirs

1              agavanzal  nª sª
2                         agrio
3           agrio (aznalcollar)
7                       aguilar
8                aguilar campoo
12                       albina
13                   alcala rio
14            alcaniz (estanca)
15                    alcantara
16                   alcollarin
19                   alfilorios
22                    algeciras
23            algeciras  rambla
28               alsa   mediajo
29                  alsa torina
32                   anchuricas
36                        arcos
37               arcos frontera
46             bachimana (lago)
47               bachimana alto
49                        banos
50             banos montemayor
51                          bao
54                        barca
59                     bautista
60                bayco  rambla
65                    benageber
67                      beninar
70                     boadella
76              bramatuero alto
77                        brena
78                     brena ii
82                       bujeda
83                      burdalo
85                    burguillo
86     burguillo   puente nuevo
87                        buseo
88                    cabezuela
89          caceres   guadiloba
92                  caldas reis
97               campos paraiso
102              canon santolea
103                  cantillana
104                      carpio
108                    caspe ii
111                    castrelo
112               castrelo mino
116                     catllar
119                     cecebre
125                  certescans
127                   chandreja
128                   chandrexa
134                     cohilla
135                      colada
143                    cornalbo
152            darnius boadella
153       derivacion retortillo
155                dona aldonza
157                  edrada mao
158                       eiras
160                      enciso
167                      ferial
169                    fervenza
171                       fitas
172                        foix
174                forcadas  as
186                       grado
187                     grado i
191                 guadalhorce
192      guadalhorce guadalteba
195                  guadalteba
197                   guadiloba
200            guijo granadilla
201                    guillena
202                   guistolas
203                hornachuelos
208                       ibiur
209                     ibon ip
210                          ip
218                       jerte
219           jerte   plasencia
220               jose bautista
222                  juan benet
223                  lago negro
226                     lebrija
227                     lechago
231                     llerena
234                 loteta (la)
237        malpasillo ( jauja )
238            malpasillo jauja
239                   malvecino
241             manzanares real
242                  mar (lago)
244                 marisanchez
245                   marmolejo
246              martin gonzalo
248                     mediajo
250                   melonares
251                  mequinenza
253              molino chincha
254                     molinos
255            molinos matachel
256                      moneva
257                  monteagudo
258         monteagudo vicarias
262                     montoro
263                       muela
264                      nagore
265                   naranjero
270                negro (lago)
272    nuestra senora agavanzal
273                       odiel
275                   olivargas
281                parras (las)
282                      peares
283                  peares  os
285                 pedro marin
290          pias (san agustin)
297          porma (juan benet)
298                     portaje
304                  proserpina
305           pto  vallehermoso
309             puente santolea
310                     puentes
311                  puentes iv
313         puerto vallehermoso
316                     rabanos
324                  ribeira  a
326                     riocobo
327                    riolobos
328                     rioseco
332                      rodeos
338               saburo (lago)
340                      salime
343                 san  estevo
345               san bartolome
349                 san lorenzo
350                 san martino
352        san rafael navallana
353                san salvador
356                   sant ponc
357                   sant pons
362                  santillana
373                       siles
374       sistema aguas limpias
375       sistema alto caldares
376            sistema capdella
377             sistema escarra
378         sistema lagos espot
379          sistema valle aran
381             somiedo (lagos)
382                      sotiel
384                    sta uxia
388                      talarn
391                    tentudia
392                   terradets
393                     terroba
397               torre abraham
398               torre abrahan
400    torrejon (tajo   tietar)
401                 tort (lago)
402                        tous
403               tous   ribera
406              tremp o talarn
410                    urdiceto
421                  valdepatao
427         vellon (pedrezuela)
428                     vencias
430                     vicario
431                   vilagudin
433                 villafranca
435                  villagudin
436             villalba barros
441                   villaseca
445                      zahara
446               zahara gastor
448                       zufre
Name: name, dtype: object

In [5]:
pd.reset_option('display.max_rows')

In [6]:
paired_reservoirs = merged_pd[(merged_pd['id'].notnull()) & (merged_pd['x'].notnull())]['name'].copy()
paired_reservoirs.sort_values(inplace=True)
len(paired_reservoirs)

273

In [7]:
print(f"Remember that reservoirs_pd has {len(reservoirs_pd)} rows and detailed_reservoirs_pd has {len(detailed_reservoirs_pd)} rows")

Remember that reservoirs_pd has 401 rows and detailed_reservoirs_pd has 320 rows

In [8]:
# As detailed_reservoirs_pd has less reservoirs, we will focus on its not paired ones
not_paired_from_detailed = merged_pd[merged_pd['id'].isnull()]['name'].copy()
not_paired_from_detailed.sort_values(inplace=True)
pd.set_option('display.max_rows', None)
not_paired_from_detailed

2                         agrio
8                aguilar campoo
23            algeciras  rambla
29                  alsa torina
36                        arcos
47               bachimana alto
50             banos montemayor
59                     bautista
60                bayco  rambla
82                       bujeda
85                    burguillo
92                  caldas reis
97               campos paraiso
108                    caspe ii
112               castrelo mino
127                   chandreja
152            darnius boadella
167                      ferial
187                     grado i
191                 guadalhorce
195                  guadalteba
197                   guadiloba
209                     ibon ip
218                       jerte
220               jose bautista
222                  juan benet
223                  lago negro
226                     lebrija
238            malpasillo jauja
239                   malvecino
241             manzanares real
244                 marisanchez
248                     mediajo
255            molinos matachel
258         monteagudo vicarias
272    nuestra senora agavanzal
282                      peares
311                  puentes iv
313         puerto vallehermoso
327                    riolobos
332                      rodeos
356                   sant ponc
382                      sotiel
388                      talarn
397               torre abraham
402                        tous
431                   vilagudin
441                   villaseca
445                      zahara
Name: name, dtype: object

In [9]:
pd.reset_option('display.max_rows')

In [10]:
# Repeated from detailed:
repeated_in_detailed = ['agrio', 'aguilar campoo', 'algeciras  rambla', 'arcos', 'bachimana alto', 'banos montemayor', 'burguillo', 'castrelo mino', 'chandreja', 'grado i', 'guadalteba', 'ibon ip', 'jerte', 'malpasillo jauja', 'molinos matachel', 'monteagudo vicarias', 'lago negro', 'peares', 'puentes iv', 'sant ponc', 'torre abraham', 'tous', 'vilagudin', 'zahara', 'juan benet']
repeated_in_reservoirs = ['agrio (aznalcollar)', 'aguilar', 'algeciras', 'arcos frontera', 'bachimana (lago)', 'banos', 'burguillo   puente nuevo', 'castrelo', 'chandrexa', 'grado', 'guadalhorce guadalteba', 'ip', 'jerte   plasencia', 'malpasillo ( jauja )', 'molinos', 'vicarias', 'negro (lago)', 'peares  os', 'puentes', 'sant pons', 'torre abrahan', 'tous   ribera', 'villagudin', 'zahara gastor', 'porma (juan benet)']

In [11]:
series_repeated = pd.Series(repeated_in_detailed, index=repeated_in_reservoirs)
series_repeated

agrio (aznalcollar)                       agrio
aguilar                          aguilar campoo
algeciras                     algeciras  rambla
arcos frontera                            arcos
bachimana (lago)                 bachimana alto
banos                          banos montemayor
burguillo   puente nuevo              burguillo
castrelo                          castrelo mino
chandrexa                             chandreja
grado                                   grado i
guadalhorce guadalteba               guadalteba
ip                                      ibon ip
jerte   plasencia                         jerte
malpasillo ( jauja )           malpasillo jauja
molinos                        molinos matachel
vicarias                    monteagudo vicarias
negro (lago)                         lago negro
peares  os                               peares
puentes                              puentes iv
sant pons                             sant ponc
torre abrahan                     torre abraham
tous   ribera                              tous
villagudin                            vilagudin
zahara gastor                            zahara
porma (juan benet)                   juan benet
dtype: object

In [12]:
# We remain with the dataframe reservoirs as the left one, because it has the ID so that it can be paired with water.csv
reservoirs_pd['name'] = reservoirs_pd['name'].map(series_repeated).fillna(reservoirs_pd['name'])
reservoirs_pd

,id,scope,name,capacity,electric_flag
0,1,guadalquivir,brena,103,0
1,3,guadalquivir,fernandina,247,0
2,5,guadalquivir,puebla cazalla,87,0
3,6,guadalquivir,pedro marin,19,0
4,9,cuenca mediterranea andaluza,vinuela,170,0
...,...,...,...,...,...
396,735,jucar,bellus,69,0
397,739,ebro,laverne,38,0
398,741,ebro,pena,19,0
399,743,ebro,santa maria belsue,14,0
400,744,galicia costa,vilagudin,18,0

In [13]:
final_merged_df = pd.merge(reservoirs_pd, detailed_reservoirs_pd, how='left', on='name')
final_merged_df.head()

,id,scope,name,capacity,electric_flag,x,y,basin,riverbed,google,openstreetmap,wikidata,province,autonomous_community,type,crest_elevation,dam_height,report
0,1,guadalquivir,brena,103,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,guadalquivir,fernandina,247,0,38.179646,-3.570224,guadalquivir,rio guarrizas,NaN,NaN,NaN,jaen,andalucia,presa fabrica gravedad (hormigon vibrado),719.55,NaN,https://sig.mapama.gob.es/WebServices/clientew...
2,5,guadalquivir,puebla cazalla,87,0,37.129772,-5.243309,guadalquivir,rio corbones,NaN,NaN,NaN,sevilla,andalucia,presa fabrica gravedad (hormigon compactado),218.25,NaN,https://sig.mapama.gob.es/WebServices/clientew...
3,6,guadalquivir,pedro marin,19,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9,cuenca mediterranea andaluza,vinuela,170,0,36.860400,-4.164435,cuencas mediterraneas andaluzas,rio guaro,https://www.google.com/search?kgmid=/g/120jr2sh,NaN,https://www.wikidata.org/wiki/Q5830515,malaga,andalucia,presa materiales sueltos pantalla hormigon,426.00,NaN,https://sig.mapama.gob.es/WebServices/clientew...

In [14]:
len(final_merged_df[final_merged_df['x'].notna()])

297

In [15]:
final_merged_df.rename(columns={'x': 'latitude', 'y': 'longitude'}, inplace=True)

### Imputing missing values with Scrapping

In [16]:
# Imputing missing values with Scrapping with vectorized solution only if NaN
mask = final_merged_df['province'].isna()
final_merged_df['province'] = final_merged_df['province'].where(final_merged_df['province'].notna(), final_merged_df['name'].apply(get_reservoir_province_rate_limited))

In [17]:
pd.set_option('display.max_rows', None)

In [20]:
final_merged_df.loc[mask][['name', 'province']]

                         name     province
0                       brena      cordoba
3                 pedro marin         jaen
6                     burdalo      caceres
7                   cabezuela  ciudad real
24            puente santolea       teruel
25               san salvador       huesca
27        sistema lagos espot       lleida
45                     moneva     zaragoza
46                    cecebre    la coruna
49                   boadella       girona
53                      zufre         leon
59                 edrada mao       orense
68                 anchuricas         jaen
73                      fitas       huesca
75           sistema capdella       lleida
77                      barca     asturias
78                     carpio      cordoba
79               dona aldonza         jaen
83                  marmolejo         jaen
85                      siles         jaen
93                    vencias      segovia
94        caceres   guadiloba      caceres
105                   rioseco     asturias
108              hornachuelos      cordoba
111                   vicario  ciudad real
113                   llerena      badajoz
114         pto  vallehermoso  ciudad real
116                valdepatao       huesca
117                   terroba     la rioja
120                   montoro  ciudad real
126                  tentudia      badajoz
133          guijo granadilla      caceres
138                monteagudo        soria
141               san lorenzo   las palmas
143     derivacion retortillo      cordoba
144                  guillena      sevilla
146               villafranca      cordoba
149                alcollarin      caceres
159                certescans         None
161                mar (lago)         leon
162                  sta uxia       orense
165                   beninar      almeria
173           villalba barros      badajoz
176          agavanzal  nª sª       zamora
178                 alcantara      caceres
179                santillana       madrid
181                     buseo     valencia
184     sistema aguas limpias       huesca
186                  urdiceto       huesca
187              forcadas  as    la coruna
196                 guistolas       orense
197               san martino      caceres
205               loteta (la)     zaragoza
209                   cohilla    cantabria
210                    salime     asturias
212                  brena ii      cordoba
221        pias (san agustin)       orense
225            molino chincha       cuenca
231                    nagore      navarra
232                mequinenza     zaragoza
233            alsa   mediajo    cantabria
236        sistema valle aran       huesca
238                     ibiur    guipuzcoa
243                    albina        alava
247                 terradets       lleida
249                 melonares      sevilla
251      san rafael navallana      cordoba
256                   rabanos        soria
264             san bartolome     zaragoza
265     sistema alto caldares       huesca
267                alfilorios     asturias
268            martin gonzalo      cordoba
275                 olivargas       huelva
282       vellon (pedrezuela)         None
284                 benageber     valencia
286                 naranjero     valencia
287                     muela     valencia
291           bramatuero alto       huesca
293                    enciso     la rioja
295                  fervenza    la coruna
296                ribeira  a    la coruna
298                   riocobo         lugo
302                cantillana      sevilla
316  torrejon (tajo   tietar)      caceres
322            canon santolea       teruel
323             saburo (lago)       lleida
324              parras (las)       teruel
327                   catllar    tarragona
328                      foix    tarragona
329           sistema escarra       huesca
332           somiedo (lagos)     asturias
352         alcaniz (estanca)       teruel
356                     eiras   pontevedra
357            tremp o talarn       lleida
362                  cornalbo         None
364                    colada      cordoba
366                proserpina      badajoz
376                   lechago         None
378               tort (lago)      cordoba
379                alcala rio      sevilla
382                     odiel       huelva
383                       bao       orense
384               san  estevo      caceres
392                   portaje      caceres

In [28]:
pd.reset_option('display.max_rows')

#### Importing the None ones

In [23]:
final_merged_df[final_merged_df['province'].isnull()]

,id,scope,name,capacity,electric_flag,latitude,longitude,basin,riverbed,google,openstreetmap,wikidata,province,autonomous_community,type,crest_elevation,dam_height,report
159,312,ebro,certescans,16,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN
282,536,tajo,vellon (pedrezuela),41,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN
362,669,guadiana,cornalbo,11,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN
376,688,ebro,lechago,18,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN

In [24]:
mask_None = final_merged_df['province'].isnull()
name_None = ['certescans', 'vellon (pedrezuela)', 'cornalbo', 'lechago']
province_None = ['lleida', 'madrid', 'badajoz', 'teruel']
series_None = pd.Series(province_None, index=name_None)
final_merged_df['province'] = final_merged_df['province'].where(final_merged_df['province'].notna(), final_merged_df['name'].map(series_None))
final_merged_df[mask_None]

,id,scope,name,capacity,electric_flag,latitude,longitude,basin,riverbed,google,openstreetmap,wikidata,province,autonomous_community,type,crest_elevation,dam_height,report
159,312,ebro,certescans,16,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,lleida,NaN,NaN,NaN,NaN,NaN
282,536,tajo,vellon (pedrezuela),41,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,madrid,NaN,NaN,NaN,NaN,NaN
362,669,guadiana,cornalbo,11,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,badajoz,NaN,NaN,NaN,NaN,NaN
376,688,ebro,lechago,18,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,teruel,NaN,NaN,NaN,NaN,NaN

### Unify the province names

In [33]:
final_merged_df['province'].sort_values().unique()

array(['a coruna', 'alacant alicante', 'alava', 'albacete', 'almeria',
       'araba alava', 'asturias', 'avila', 'badajoz', 'barcelona',
       'burgos', 'caceres', 'cadiz', 'cantabria', 'castello castellon',
       'ciudad real', 'cordoba', 'cuenca', 'gipuzkoa guipuzcoa', 'girona',
       'granada', 'guadalajara', 'guipuzcoa', 'huelva', 'huesca', 'jaen',
       'la coruna', 'la rioja', 'las palmas', 'leon', 'lleida', 'lugo',
       'madrid', 'malaga', 'murcia', 'navarra', 'orense', 'ourense',
       'palencia', 'pontevedra', 'rioja', 'salamanca', 'segovia',
       'sevilla', 'soria', 'tarragona', 'teruel', 'toledo', 'valencia',
       'valladolid', 'valència valencia', 'zamora', 'zaragoza'],
      dtype=object)

In [40]:
unified_provinces = {
    'alacant alicante': 'alicante',
    'araba alava': 'alava',
    'castello castellon': 'castellon',
    'gipuzkoa guipuzcoa': 'guipuzcoa',
    'ourense': 'orense',
    'valència valencia': 'valencia',
    'a coruna': 'la coruna',
    'rioja': 'la rioja'
}

final_merged_df['province'] = final_merged_df['province'].map(unified_provinces).fillna(final_merged_df['province'])
final_merged_df['province'].sort_values().unique()

array(['alava', 'albacete', 'alicante', 'almeria', 'asturias', 'avila',
       'badajoz', 'barcelona', 'burgos', 'caceres', 'cadiz', 'cantabria',
       'castellon', 'ciudad real', 'cordoba', 'cuenca', 'girona',
       'granada', 'guadalajara', 'guipuzcoa', 'huelva', 'huesca', 'jaen',
       'la coruna', 'la rioja', 'las palmas', 'leon', 'lleida', 'lugo',
       'madrid', 'malaga', 'murcia', 'navarra', 'orense', 'palencia',
       'pontevedra', 'salamanca', 'segovia', 'sevilla', 'soria',
       'tarragona', 'teruel', 'toledo', 'valencia', 'valladolid',
       'zamora', 'zaragoza'], dtype=object)

In [43]:
province_to_community = {
    'alava': 'pais vasco',
    'albacete': 'castilla   mancha',
    'alicante': 'comunitat valenciana',
    'almeria': 'andalucia',
    'asturias': 'principado asturias',
    'avila': 'castilla y leon',
    'badajoz': 'extremadura',
    'barcelona': 'cataluna',
    'burgos': 'castilla y leon',
    'caceres': 'extremadura',
    'cadiz': 'andalucia',
    'cantabria': 'cantabria',
    'castellon': 'comunitat valenciana',
    'ciudad real': 'castilla   mancha',
    'cordoba': 'andalucia',
    'cuenca': 'castilla   mancha',
    'girona': 'cataluna',
    'granada': 'andalucia',
    'guadalajara': 'castilla   mancha',
    'guipuzcoa': 'pais vasco',
    'huelva': 'andalucia',
    'huesca': 'aragon',
    'jaen': 'andalucia',
    'la coruna': 'galicia',
    'la rioja': 'rioja',
    'las palmas': 'canarias',
    'leon': 'castilla y leon',
    'lleida': 'cataluna',
    'lugo': 'galicia',
    'madrid': 'comunidad madrid',
    'malaga': 'andalucia',
    'murcia': 'region murcia',
    'navarra': 'comunidad foral navarra',
    'orense': 'galicia',
    'palencia': 'castilla y leon',
    'pontevedra': 'galicia',
    'salamanca': 'castilla y leon',
    'santa cruz de tenerife': 'canarias',
    'segovia': 'castilla y leon',
    'sevilla': 'andalucia',
    'soria': 'castilla y leon',
    'tarragona': 'cataluna',
    'teruel': 'aragon',
    'toledo': 'castilla   mancha',
    'valencia': 'comunitat valenciana',
    'valladolid': 'castilla y leon',
    'vizcaya': 'pais vasco',
    'zamora': 'castilla y leon',
    'ceuta': 'ceuta',
    'melilla': 'melilla',
    'balears': 'islas baleares',
    'zaragoza': 'aragon'
}

final_merged_df['autonomous_community'] = final_merged_df['province'].map(province_to_community)
final_merged_df[['province', 'autonomous_community']].drop_duplicates().sort_values('province')

        province     autonomous_community
76         alava               pais vasco
14      albacete        castilla   mancha
18      alicante     comunitat valenciana
165      almeria                andalucia
77      asturias      principado asturias
11         avila          castilla y leon
55       badajoz              extremadura
163    barcelona                 cataluna
29        burgos          castilla y leon
6        caceres              extremadura
54         cadiz                andalucia
72     cantabria                cantabria
15     castellon     comunitat valenciana
7    ciudad real        castilla   mancha
0        cordoba                andalucia
17        cuenca        castilla   mancha
49        girona                 cataluna
5        granada                andalucia
12   guadalajara        castilla   mancha
164    guipuzcoa               pais vasco
34        huelva                andalucia
20        huesca                   aragon
1           jaen                andalucia
46     la coruna                  galicia
43      la rioja                    rioja
141   las palmas                 canarias
53          leon          castilla y leon
23        lleida                 cataluna
10          lugo                  galicia
66        madrid         comunidad madrid
4         malaga                andalucia
98        murcia            region murcia
26       navarra  comunidad foral navarra
8         orense                  galicia
60      palencia          castilla y leon
48    pontevedra                  galicia
41     salamanca          castilla y leon
39       segovia          castilla y leon
2        sevilla                andalucia
40         soria          castilla y leon
47     tarragona                 cataluna
21        teruel                   aragon
63        toledo        castilla   mancha
16      valencia     comunitat valenciana
130   valladolid          castilla y leon
65        zamora          castilla y leon
45      zaragoza                   aragon

In [44]:
final_merged_df['autonomous_community'].unique()

array(['andalucia', 'extremadura', 'castilla   mancha', 'galicia',
       'castilla y leon', 'comunitat valenciana', 'aragon', 'cataluna',
       'comunidad foral navarra', 'rioja', 'comunidad madrid',
       'cantabria', 'pais vasco', 'principado asturias', 'region murcia',
       'canarias'], dtype=object)

In [45]:
# Save the merged DataFrame
merged_reservoirs_path = PATHS['cleaned_data'] / 'reservoirs_merged.csv'
merged_reservoirs_path.parent.mkdir(parents=True, exist_ok=True)
final_merged_df.to_csv(merged_reservoirs_path, index=False)

In [46]:
final_merged_df.head()

,id,scope,name,capacity,electric_flag,latitude,longitude,basin,riverbed,google,openstreetmap,wikidata,province,autonomous_community,type,crest_elevation,dam_height,report
0,1,guadalquivir,brena,103,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cordoba,andalucia,NaN,NaN,NaN,NaN
1,3,guadalquivir,fernandina,247,0,38.179646,-3.570224,guadalquivir,rio guarrizas,NaN,NaN,NaN,jaen,andalucia,presa fabrica gravedad (hormigon vibrado),719.55,NaN,https://sig.mapama.gob.es/WebServices/clientew...
2,5,guadalquivir,puebla cazalla,87,0,37.129772,-5.243309,guadalquivir,rio corbones,NaN,NaN,NaN,sevilla,andalucia,presa fabrica gravedad (hormigon compactado),218.25,NaN,https://sig.mapama.gob.es/WebServices/clientew...
3,6,guadalquivir,pedro marin,19,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,jaen,andalucia,NaN,NaN,NaN,NaN
4,9,cuenca mediterranea andaluza,vinuela,170,0,36.860400,-4.164435,cuencas mediterraneas andaluzas,rio guaro,https://www.google.com/search?kgmid=/g/120jr2sh,NaN,https://www.wikidata.org/wiki/Q5830515,malaga,andalucia,presa materiales sueltos pantalla hormigon,426.00,NaN,https://sig.mapama.gob.es/WebServices/clientew...

In [51]:
final_merged_df['autonomous_community'].value_counts()

autonomous_community
andalucia                  91
aragon                     47
castilla y leon            45
extremadura                45
castilla   mancha          39
galicia                    34
cataluna                   25
comunitat valenciana       21
comunidad madrid           13
comunidad foral navarra     8
principado asturias         8
pais vasco                  8
region murcia               8
rioja                       5
cantabria                   3
canarias                    1
Name: count, dtype: int64

In [52]:
final_merged_df['province'].value_counts()

province
huesca         28
caceres        23
badajoz        22
jaen           19
cordoba        18
orense         18
sevilla        15
lleida         15
madrid         13
toledo         11
leon           11
valencia       11
granada        11
ciudad real    10
huelva         10
cadiz          10
zaragoza       10
guadalajara     9
teruel          9
navarra         8
murcia          8
asturias        8
lugo            7
salamanca       7
zamora          7
la coruna       7
tarragona       6
malaga          6
palencia        5
castellon       5
cuenca          5
la rioja        5
alicante        5
albacete        4
avila           4
segovia         4
alava           4
guipuzcoa       4
burgos          3
soria           3
cantabria       3
girona          2
pontevedra      2
almeria         2
barcelona       2
valladolid      1
las palmas      1
Name: count, dtype: int64